name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Instalar dependencias
        working-directory: front
        run: npm ci
      - name: Pasar prettier
        working-directory: front
        run: npm run prettier
      - name: Generar build
        working-directory: front
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: AIzaSyCDzqlxdYZYIVg8x7-PPC3DIZ8OwuuTKKY
